add curly brackets
```
build.sbt:7: error: No implicit for Append.Values[Seq[sbt.ModuleID], Option[(Int, Int)]] found,
  so Option[(Int, Int)] cannot be appended to Seq[sbt.ModuleID]
libraryDependencies ++=
                    ^
build.sbt:9: error: value >= is not a member of Any
    case Some((2, minor)) if minor >= 13 =>
                                   ^
build.sbt:10: error: type mismatch;
 found   : Seq[sbt.ModuleID]
 required: sbt.internals.DslEntry
      Seq("org.scala-lang.modules" %% "scala-parallel-collections" % "0.1.2")
         ^
[error] Type error in expression
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? q
```